language: node_js

dist: trusty

git:
  submodules: true

node_js:
  - '12'

install:
  - npm i

script:
  - npm run lint
  - npm test

before_deploy:
  - npm run build:storybook
  - mv docs/* .

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
