language: node_js
dist: trusty
git:
  submodules: true

node_js:
  - '12'
install:
  - npm i

stages:
  - prepare
  - name: deploy_page
    if: branch = master
  - name: deploy_npm
    if: tag IS present

jobs:
  include:
    - stage: prepare
      script:
        - npm run lint
        - npm run test
    - stage: deploy_page
      before_deploy:
        - npm run build:storybook
        - mv docs/* .
      deploy:
        provider: pages
        skip_cleanup: true
        keep_history: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
    - stage: deploy_npm
      deploy:
        provider: npm
        email: alihan.arshabekov@gmail.com
        api_key: $NPM_TOKEN
        on:
          tags: true
          all_branches: true
